import frappe

no_cache = 1


def get_context(context):
    """Boot data for the Pulse Vue SPA (www/pulse.html is generated by the build).

    The frappe-ui build injects `window[key] = boot[key]` for each key below,
    giving the SPA its CSRF token and session context for authenticated calls.
    """
    context.no_cache = 1
    context.boot = {
        "csrf_token": frappe.sessions.get_csrf_token(),
        "sitename": frappe.local.site,
        "user": frappe.session.user,
    }
    frappe.db.commit()
    return context
