/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bars: typeof import('./src/components/charts/Bars.vue')['default']
    CreateIssueModal: typeof import('./src/components/CreateIssueModal.vue')['default']
    DashboardWidget: typeof import('./src/components/DashboardWidget.vue')['default']
    Donut: typeof import('./src/components/charts/Donut.vue')['default']
    EntityForm: typeof import('./src/components/EntityForm.vue')['default']
    Gauge: typeof import('./src/components/charts/Gauge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDrawer: typeof import('./src/components/TaskDrawer.vue')['default']
  }
}
