<template>
  <section class="modules-page">
    <header class="modules-toolbar"><button v-if="detail" class="btn-ghost" @click="select(null)">← Modules</button><h1>{{ detail?.title || 'Modules' }}</h1><select v-if="!route.query.project" v-model="project" aria-label="Project"><option value="">Choose project</option><option v-for="p in projects" :value="p.name" :key="p.name">{{ p.project_name }}</option></select><input v-if="!detail" v-model="search" placeholder="Search modules" aria-label="Search modules" /><button v-if="project && !detail" class="btn-primary" @click="edit()">Add module</button><button v-if="detail?.can_write" class="btn-ghost" @click="edit(detail)">Edit module</button></header>
    <p v-if="error" role="alert" class="message">{{ error }} <button class="btn-ghost" @click="load">Retry</button></p>
    <Teleport to="body">
      <dialog v-if="draft" ref="moduleDialog" class="module-dialog" aria-labelledby="module-dialog-title" @cancel.prevent="closeDraft" @click="dismissBackdrop">
        <form class="module-form" @submit.prevent="save">
          <header class="module-dialog-header"><div><p class="module-project">{{ projects.find(p => p.name === project)?.project_name || 'Project module' }}</p><h2 id="module-dialog-title">{{ draft.name ? 'Edit module' : 'Add module' }}</h2><p>Group related tasks and track their progress together.</p></div><button type="button" class="module-close" aria-label="Close module form" :disabled="busy" @click="closeDraft"><X /></button></header>
          <div class="module-fields">
            <p v-if="formError" role="alert" class="module-error">{{ formError }}</p>
            <label>Module name <input ref="moduleName" v-model.trim="draft.title" autofocus required maxlength="140" placeholder="e.g. Website launch" :disabled="busy" /></label>
            <label>Description <span class="optional">Optional</span><textarea v-model="draft.description" rows="3" placeholder="What does this module cover?" :disabled="busy" /></label>
            <div class="properties"><label>Status<select v-model="draft.status" :disabled="busy"><option v-for="s in statuses" :key="s">{{ s }}</option></select></label><label>Lead<select v-model="draft.lead" :disabled="busy"><option value="">Unassigned</option><option v-for="u in users" :key="u.name" :value="u.name">{{ u.full_name }}</option></select></label><label>Start date<input v-model="draft.start_date" type="date" :disabled="busy" /></label><label>Due date<input v-model="draft.due_date" type="date" :min="draft.start_date" :disabled="busy" /></label></div>
          </div>
          <footer class="module-dialog-footer"><button type="button" class="btn-ghost" :disabled="busy" @click="closeDraft">Cancel</button><button class="btn-primary" :disabled="busy || !draft.title.trim()">{{ busy ? 'Saving…' : draft.name ? 'Save changes' : 'Create module' }}</button></footer>
        </form>
      </dialog>
    </Teleport>
    <p v-if="loading" class="message" role="status">Loading modules…</p>
    <div v-else-if="detail" class="module-detail">
      <div class="detail-summary"><span class="progress-ring" :style="ring(detail.percentage)"><span>{{ detail.percentage }}%</span></span><div><strong>{{ detail.completed }} of {{ detail.total }} tasks completed</strong><p>{{ detail.status }}<span v-if="detail.start_date || detail.due_date"> · {{ dates(detail) }}</span><span v-if="detail.lead"> · {{ detail.lead }}</span></p></div></div><p v-if="detail.description" class="description">{{ detail.description }}</p><p class="progress-note">Progress includes tasks you can access. Archived and cancelled tasks are excluded.</p>
      <div class="detail-actions"><RouterLink class="btn-ghost" :to="{path:'/board',query:{project,module:detail.name}}">Open all task views →</RouterLink><button v-if="detail.can_write" class="btn-ghost" @click="pick">Add existing tasks</button><button v-if="detail.can_write" class="btn-primary" @click="createTask">New task</button></div>
      <div v-if="picking" class="task-picker"><input v-model="taskSearch" placeholder="Search tasks" aria-label="Search available tasks" /><label v-for="t in filteredAvailable" :key="t.name" class="task-choice"><input type="checkbox" v-model="selected" :value="t.name" /><span class="muted">{{ t.issue_key || t.name }}</span> {{ t.subject }}</label><p v-if="!filteredAvailable.length">No available tasks match.</p><div class="actions"><button class="btn-primary" :disabled="busy || !selected.length" @click="addTasks">Add {{ selected.length || '' }} selected</button><button class="btn-ghost" @click="picking=false">Cancel</button></div></div>
      <div class="task-list"><div v-for="t in detail.tasks" :key="t.name" class="task-row"><RouterLink :to="{path:'/board',query:{project,task:t.name,module:detail.name}}"><span class="muted">{{ t.issue_key || t.name }}</span> {{ t.subject }}</RouterLink><span>{{ t.workflow_state || t.status }}</span><span>{{ t.priority }}</span><button v-if="detail.can_write" class="btn-ghost" :disabled="busy" :aria-label="`Remove ${t.subject} from module`" @click="removeTask(t.name)">Remove</button></div><p v-if="!detail.tasks.length" class="message">Add tasks to start tracking this module’s progress.</p></div>
    </div>
    <div v-else class="module-list"><button v-for="m in filtered" :key="m.name" class="module-row" @click="select(m.name)"><span class="progress-ring" :style="ring(m.percentage)"><span>{{ m.percentage }}%</span></span><strong>{{ m.title }}</strong><span class="module-dates">{{ dates(m) }}</span><span class="module-status" :data-status="m.status">{{ m.status }}</span><span class="module-lead">{{ m.lead || 'Unassigned' }}</span><span aria-hidden="true">›</span></button><div v-if="!filtered.length" class="empty"><h2>{{ project ? 'No modules yet' : 'Choose a project' }}</h2><p>Group related tasks into a feature, workstream, or milestone and track their completion.</p></div></div>
  </section>
</template>
<script setup>
import { computed,onMounted,ref,watch,nextTick } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { call } from 'frappe-ui'
import X from '~icons/lucide/x'
import { openCreate, createState } from '@/ui/create'
const route=useRoute(),router=useRouter(),project=ref(route.query.project || ''),projects=ref([]),modules=ref([]),detail=ref(null),search=ref(''),loading=ref(false),busy=ref(false),error=ref(''),draft=ref(null),users=ref([]),picking=ref(false),available=ref([]),selected=ref([]),taskSearch=ref('')
const moduleDialog=ref(null),moduleName=ref(null),formError=ref('')
function closeDraft(){if(!busy.value){moduleDialog.value?.close();draft.value=null}}
function dismissBackdrop(event){if(event.target!==moduleDialog.value)return;const box=moduleDialog.value.getBoundingClientRect();if(event.clientX<box.left || event.clientX>box.right || event.clientY<box.top || event.clientY>box.bottom)closeDraft()}
watch(draft,async value=>{if(value){await nextTick();moduleDialog.value?.showModal();moduleName.value?.focus()}}, {flush:'post'})
const statuses=['Backlog','Planned','In Progress','Paused','Completed','Cancelled']
const filtered=computed(()=>modules.value.filter(m=>m.title.toLowerCase().includes(search.value.toLowerCase())))
const filteredAvailable=computed(()=>available.value.filter(t=>`${t.issue_key} ${t.subject}`.toLowerCase().includes(taskSearch.value.toLowerCase())))
const ring=p=>({background:`conic-gradient(var(--success, #16a34a) ${p*3.6}deg, var(--border) 0deg)`})
const dates=m=>[m.start_date,m.due_date].filter(Boolean).map(d=>new Date(`${String(d).slice(0,10)}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})).join(' – ') || 'No dates'
async function load(){ if(!project.value)return;loading.value=true;error.value='';try{modules.value=await call('pulse.api.modules.list_modules',{project:project.value});detail.value=route.query.module?await call('pulse.api.modules.get_module',{name:route.query.module}):null}catch(e){error.value=e.message || 'Could not load modules.'}finally{loading.value=false}}
async function select(name){draft.value=null;picking.value=false;await router.replace({query:{...route.query,project:project.value,module:name || undefined}})}
async function edit(m){formError.value='';draft.value={name:m?.name,title:m?.title || '',description:m?.description || '',status:m?.status || 'Backlog',start_date:m?.start_date?.slice(0,10) || '',due_date:m?.due_date?.slice(0,10) || '',lead:m?.lead || ''};try{users.value=await call('pulse.api.intake.reviewer_options',{project:project.value})}catch(e){formError.value=e.message || 'Could not load project leads.'}}
async function save(){if(busy.value || !draft.value?.title.trim())return;busy.value=true;formError.value='';try{const result=await call('pulse.api.modules.save_module',{...draft.value,project:project.value});moduleDialog.value?.close();draft.value=null;await select(result.name);await load()}catch(e){formError.value=e.message || 'Module could not be saved. Please try again.'}finally{busy.value=false}}
async function pick(){try{available.value=await call('pulse.api.modules.available_tasks',{name:detail.value.name});selected.value=[];taskSearch.value='';picking.value=true}catch(e){error.value=e.message}}
async function updateTasks(tasks,remove=0){busy.value=true;error.value='';try{detail.value=await call('pulse.api.modules.set_tasks',{name:detail.value.name,tasks,remove});picking.value=false;await load()}catch(e){error.value=e.message}finally{busy.value=false}}
const addTasks=()=>updateTasks(selected.value)
const removeTask=name=>updateTasks([name],1)
function createTask(){openCreate({project:project.value,module:detail.value.name,module_name:detail.value.title})}
watch(()=>route.query,()=>{project.value=route.query.project || project.value;load()})
watch(()=>createState.created,load)
watch(project,()=>{detail.value=null;draft.value=null;load()})
onMounted(async()=>{try{projects.value=await call('frappe.client.get_list',{doctype:'Project',fields:['name','project_name'],limit_page_length:0});await load()}catch(e){error.value=e.message}})
</script>
<style scoped>
.modules-page{height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden;color:var(--text)}.modules-toolbar{display:flex;gap:10px;align-items:center;flex-shrink:0;padding:10px 20px;border-bottom:1px solid var(--border)}h1{font-size:14px;font-weight:600;margin-right:auto}.modules-toolbar input{max-width:220px}input:not([type=checkbox]),select,textarea{border:1px solid var(--border);border-radius:6px;background:var(--surface);color:var(--text);padding:7px 9px;font:inherit;min-width:0}.module-list,.module-detail{flex:1;min-height:0;overflow:auto}.module-row{width:100%;display:flex;align-items:center;gap:20px;padding:15px 24px;border-bottom:1px solid var(--border);text-align:left}.module-row:hover{background:var(--surface-2)}.module-row strong{flex:1;font-weight:500}.progress-ring{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;flex-shrink:0}.progress-ring>span{width:33px;height:33px;background:var(--surface);border-radius:50%;display:grid;place-items:center;font-size:11px;color:var(--text-muted)}.module-status{min-width:100px;text-align:center;padding:5px 8px;border-radius:5px;background:var(--surface-2);color:var(--text-muted);font-size:12px}.module-status[data-status='In Progress']{color:#b45309;background:#fff7ed}.module-status[data-status=Completed]{color:#15803d;background:#f0fdf4}.module-status[data-status=Planned]{color:var(--accent);background:var(--surface-2)}.module-dates,.module-lead{font-size:12px;color:var(--text-muted)}.module-lead{max-width:160px;overflow:hidden;text-overflow:ellipsis}.empty{padding:50px 24px;text-align:center;color:var(--text-muted)}h2{font-size:16px}.module-form{padding:18px 24px;border-bottom:1px solid var(--border);display:grid;gap:12px;overflow:auto;max-height:65vh}.module-form label{display:grid;gap:5px;font-size:12px}.properties{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.actions,.detail-actions{display:flex;gap:8px;align-items:center}.detail-summary{display:flex;gap:16px;align-items:center;padding:20px 24px 10px}.detail-summary p,.progress-note{font-size:12px;color:var(--text-muted)}.progress-note,.description,.detail-actions{margin:10px 24px}.description{white-space:pre-wrap}.task-row{display:flex;align-items:center;gap:20px;padding:10px 24px;border-bottom:1px solid var(--border);font-size:13px}.task-row a{flex:1}.muted{color:var(--text-muted);margin-right:10px}.task-picker{margin:16px 24px;padding:14px;border:1px solid var(--border);border-radius:8px;max-height:350px;overflow:auto}.task-choice{display:flex;gap:8px;padding:10px 0;align-items:center}.message{padding:12px 24px}@media(max-width:700px){.modules-toolbar{flex-wrap:wrap}.module-dates,.module-lead{display:none}.module-row{gap:12px;padding:12px}.properties{grid-template-columns:1fr 1fr}.task-row{flex-wrap:wrap}.task-row a{flex-basis:100%}.detail-actions{flex-wrap:wrap}}

.module-dialog{position:fixed;inset:0;margin:auto;width:min(560px,calc(100vw - 32px));max-height:calc(100dvh - 32px);padding:0;border:0;border-radius:12px;background:var(--surface);color:var(--text);box-shadow:0 20px 64px #0003;overflow:auto}.module-dialog::backdrop{background:#11182766}.module-dialog .module-form{padding:0;border:0;display:block;max-height:none;overflow:visible}.module-dialog-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:24px 24px 0}.module-dialog-header h2{font-size:20px;font-weight:600;line-height:1.4;margin:4px 0 6px}.module-dialog-header p{font-size:13px;color:var(--muted);margin:0}.module-dialog-header .module-project{font-size:12px}.module-close{display:grid;place-items:center;flex-shrink:0;width:32px;height:32px;border-radius:6px;color:var(--muted)}.module-close svg{width:18px;height:18px}.module-close:hover{background:var(--surface-2)}.module-fields{display:grid;gap:20px;padding:24px}.module-fields label{font-size:13px;font-weight:500;position:relative;gap:8px}.module-fields input,.module-fields select,.module-fields textarea{font-weight:400;width:100%;min-height:38px}.module-fields textarea{resize:vertical;min-height:90px}.module-fields .properties{grid-template-columns:1fr 1fr;gap:18px 16px}.optional{position:absolute;right:0;top:0;font-weight:400;font-size:12px;color:var(--muted)}.module-dialog-footer{display:flex;justify-content:flex-end;gap:8px;padding:16px 24px;border-top:1px solid var(--border);background:var(--surface-2)}.module-dialog-footer button{min-height:36px;padding:8px 14px}.module-dialog :is(input,textarea,select,button):focus-visible{outline:2px solid var(--accent);outline-offset:2px}.module-dialog button:disabled{opacity:.55;cursor:not-allowed}.module-error{color:var(--danger);font-size:13px;margin:0}.module-dialog input::placeholder,.module-dialog textarea::placeholder{color:var(--muted)}@media(max-width:480px){.module-dialog-header{padding:20px 16px 0}.module-fields{padding:20px 16px}.module-fields .properties{grid-template-columns:1fr}.module-dialog-footer{padding:12px 16px}}
</style>
